### ISSUE TITLE
JLCPCB: D6,D7,D8,TP1,TP2 designators don't exist in the BOM file

### ISSUE THREAD

**Issue by Breina** [jkyprian/ebus2usb#1]
Forgive me asking stupid questions. I understand D6, D7 and D8 are LED's that I will solder myself, but TP1 and TP2 don't seem to appear anywhere. Should they be removed from `positions.csv`?

![image](https://github.com/jkyprian/ebus2usb/assets/3009914/2bf5d7ce-9284-45e1-bdcf-83e810f92db7)

**Comment by jkyprian** [comment]
T1 and T2 are just test points for GND2 and GND1 and can be ignored.
![image](https://github.com/jkyprian/ebus2usb/assets/1710378/f279b0ca-bd14-49a3-9581-130d2714b0e6)
They are convenient to hook up ground of an oscilloscope or multimeter. 
![image](https://github.com/jkyprian/ebus2usb/assets/1710378/3560e91d-5931-4589-97fb-6f28b4b19191)
